/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vennData;

import org.junit.Test;
import static org.junit.Assert.*;

import vennData.MatrixDiagram;

public class MatrixDiagramTest {
	
	MatrixDiagram md;
	
    @Test public void testMatrixDiagram_size() {
        md = new MatrixDiagram();
        assertTrue("Size is default 2", md.getSize() == 2);
    }
}
